ticketeer/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ticketeer.website.urls')),
]

ticketeer/website/orders/urls.py
from xml.etree.ElementInclude import include
from django.urls import path
from .views import search_trip


app_name = 'orders'

urlpatterns = [
    path('search/', search_trip, name='search_trip'),
]

ticketeer/website/urls.py
from django.urls import include,path
from .views import index, login, logout, register


app_name = 'website'

urlpatterns = [
    path('', index, name='index'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('orders/', include('ticketeer.website.orders.urls')),
]

ticketeer/website/forms.py
from typing import Any, Dict, Optional

from django import forms
from django.contrib.auth.password_validation import validate_password

from ticketeer.apps.users.models import User


class LoginForm(forms.Form):
    identifier = forms.EmailField(label='Email', widget=forms.TextInput(attrs={'placeholder': 'Email Anda'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password Anda'}))

    def authenticate(self) -> Optional[User]:
        identifier = self.cleaned_data.get('identifier')
        password = self.cleaned_data.get('password')
        
        try:
            user = User.objects.get(email=identifier)
            
            if user.check_password(password):
                return user
        except User.DoesNotExist:
            return None
        return None


class RegistrationForm(forms.Form):
    name = forms.CharField(label='Nama', widget=forms.TextInput(attrs={'placeholder': 'Nama Lengkap'}))
    email = forms.EmailField(label='Email', widget=forms.TextInput(attrs={'placeholder': 'Email Anda'}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput())
    password2 = forms.CharField(label='Konfirmasi Password', widget=forms.PasswordInput())
    
    def clean_password(self) -> str:
        password = self.cleaned_data.get('password')
        validate_password(password)
        return password
    
    def clean(self) -> Dict[str, Any]:
        data = super().clean()
        if self.errors:
            return data
        
        email = data.get('email')
        password = data.get('password')
        password2 = data.get('password2')

        if User.objects.filter(email=email).exists():
            self.add_error('email', forms.ValidationError('Akun dengan email ini telah tersedia.', 'duplicate_email'))

        if password != password2:
            self.add_error('password2', forms.ValidationError('Password does not match.', 'password_mismatch'))

        return data
    
    def save(self) -> User:
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        password = self.cleaned_data['password']

        return User.objects.create_user(
            name=name, email=email, password=password
        )

ticketeer/website/orders/forms.py
from typing import Any, Dict, Optional

from django import forms
from django.db.models import Q

from ticketeer.apps.users.models import User
from ticketeer.apps.trips.models import Trip


class SearchForm(forms.Form):
    origin = forms.ModelChoiceField(queryset=Trip.objects.all().values_list('origin', flat=True).distinct())
    destination = forms.ModelChoiceField(queryset=Trip.objects.all().values_list('destination', flat=True).distinct())
    transportation = forms.ModelChoiceField(queryset=Trip.objects.all().values_list('transportation', flat=True).distinct())
    
    def clean(self) -> dict:
        cleaned_data = super().clean()
        if self.errors:
            return cleaned_data
        
        return cleaned_data

ticketeer/website/orders/views.py
from datetime import datetime

from django.http import HttpRequest, JsonResponse
from django.db.models import Q

from ticketeer.apps.trips.models import Trip
from ticketeer.website.orders.forms import SearchForm


def search_trip(request: HttpRequest) -> JsonResponse:
    form = SearchForm(data=request.POST or None, trip=Trip)

    origin = form.data.get('origin')
    destination = form.data.get('destination')
    transportation = form.data.get('transportation')

    date_time_day = form.data.get('day')
    date_time_month = form.data.get('month')
    date_time_year = form.data.get('year')
    date_time_hour = form.data.get('hour')
    date_time_minute = form.data.get('minute')

    date = datetime.strptime(f'{date_time_year}-{date_time_month}-{date_time_day}', '%Y-%m-%d').date()
    time = datetime.strptime(f'{date_time_hour}:{date_time_minute}:00', '%H:%M:%S').time()
    
    trips = Trip.objects.filter(
        Q(origin=origin) &
        Q(destination=destination) &
        Q(transportation=transportation) &
        Q(departure_date=date) &
        Q(departure_time__gte=time)
    )

    if trips:
        print(trips)
        response = {
            'status_code': 200,
            'data': list(trips.values('origin', 'destination', 'transportation__name',
                                      'departure_date', 'departure_time', 'price',
                                      'available_seats')),
        }

        return JsonResponse(response, safe=False)
    else:
        response = {
            'status_code': 400,
            'message': 'Data Tidak Tersedia.'
        }

        return JsonResponse(response)

ticketeer/website/views.py
from django.http import HttpRequest, HttpResponse
from django.contrib.auth import login as django_login, logout as django_logout
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect, render

from ticketeer.apps.trips.models import Trip
from ticketeer.website.orders.forms import SearchForm

from .forms import LoginForm, RegistrationForm


def index(request: HttpRequest) -> HttpResponse:
    form = SearchForm(data=request.POST or None, trip=Trip)        
    
    context = {
        'title': 'Ticketeer - Index',
        'app': 'Ticketeer',
        'search_form': form,
    }

    return render(request, 'website/index.html', context)


def login(request: HttpRequest) -> HttpResponse:
    if not request.user.is_authenticated:
        form = LoginForm(data=request.POST or None)

        if form.is_valid():
            user = form.authenticate()
            if user:
                django_login(request, user)
                return redirect('website:index')

        context = {
            'title': 'Login',
            'form': form,
        }

        return render(request, 'website/login.html', context)
    else:
        return redirect('website:index')


def logout(request: HttpRequest) -> HttpResponse:
    django_logout(request)
    return redirect('website:index')


def register(request: HttpRequest) -> HttpResponse:
    if not request.user.is_authenticated:
        form = RegistrationForm(data=request.POST or None)

        if form.is_valid():
            user = form.save()
            response = redirect('website:index')
            django_login(request, user)
            return response
        
        context = {
            'title': 'Ticketeer - Registration',
            'form': form,
        }

        return render(request, 'website/register.html', context)
    else:
        return redirect('website:index')

templates/website/form.html
<form method="POST">
    {% csrf_token %}
    {% if request.path == '/login/' %}
        <div class="mb-3">
            <label for="{{ form.identifier.id_for_label }}" class="form-label">{{ form.identifier.label }}</label>
            <input type="email" class="form-control" id="{{ form.identifier.id_for_label }}" name="{{ form.identifier.name }}"
                placeholder="Email Anda" aria-describedby="emailHelp">
            <div id="emailHelp" class="form-text">{{ form.identifier.errors }}</div>
        </div>
        <div class="mb-3">
            <label for="{{ form.password.id_for_label }}" class="form-label">{{ form.password.label }}</label>
            <input type="password" class="form-control" id="{{ form.password.id_for_label }}"  name="{{ form.password.name }}"
                aria-describedby="emailHelp">
            <div id="emailHelp" class="form-text">{{ form.password.errors }}</div>
        </div>
    {% elif request.path == '/register/' %}
        <div class="mb-3">
            <label for="{{ form.name.id_for_label }}" class="form-label">{{ form.name.label }}</label>
            <input type="text" class="form-control" id="{{ form.name.id_for_label }}" name="{{ form.name.name }}"
                placeholder="Nama Lengkap" aria-describedby="emailHelp">
            <div id="emailHelp" class="form-text">{{ form.name.errors }}</div>
        </div>
        <div class="mb-3">
            <label for="{{ form.email.id_for_label }}" class="form-label">{{ form.email.label }}</label>
            <input type="email" class="form-control" id="{{ form.email.id_for_label }}" name="{{ form.email.name }}"
                placeholder="Email Anda" aria-describedby="emailHelp">
            <div id="emailHelp" class="form-text">{{ form.email.errors }}</div>
        </div>
        <div class="mb-3">
            <label for="{{ form.password.id_for_label }}" class="form-label">{{ form.password.label }}</label>
            <input type="password" class="form-control" id="{{ form.password.id_for_label }}" name="{{ form.password.name }}"
                aria-describedby="passwordHelp">
            <div id="passwordHelp" class="form-text">{{ form.password.errors }}</div>
        </div>
        <div class="mb-3">
            <label for="{{ form.password2.id_for_label }}" class="form-label">{{ form.password2.label }}</label>
            <input type="password" class="form-control" id="{{ form.password2.id_for_label }}" name="{{ form.password2.name }}"
                aria-describedby="passwordHelp">
            <div id="passwordHelp" class="form-text">{{ form.password2.errors }}</div>
        </div>
    {% endif %}

    <button type="submit" class="btn btn-secondary">Submit</button>
</form>

templates/website/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<header class="masthead bg-primary text-white text-center">
    <div class="container d-flex align-items-center flex-column">
        <!-- Masthead Avatar Image-->
        <img class="masthead-avatar mb-5" src="{% static 'img/avataaars.svg' %}" alt="..." />
        <!-- Masthead Heading-->
        <h1 class="masthead-heading text-uppercase mb-0">{{ app }}</h1>
        <!-- Icon Divider-->
        <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>
        <!-- Masthead Subheading-->
        <p class="masthead-subheading font-weight-light mb-0">Aplikasi Pemesanan Tiket Mudik</p>
    </div>
</header>

<section class="page-section bg-secondary text-white mb-0" id="about">
    <div class="container">
        <!-- About Section Heading-->
        <h2 class="page-section-heading text-center text-uppercase text-white">Tentang Kami</h2>
        <!-- Icon Divider-->
        <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>
        <!-- About Section Content-->
        <div class="row">
            <div class="col-8 mx-auto text-center">
                <p class="lead">Ticketeer adalah sebuah aplikasi pemesanan tiket mudik berbasis website yang menawarkan berbagai
                    macam sarana transportasi dengan harga terjangkau.
                </p>
            </div>
        </div>
        <div class="row py-md-3">
            <div class="col-lg-4 mb-md-0 mb-2 d-flex justify-content-center">
                <div class="card p-3 bg-primary" style="width: 18rem;">
                    <img src="{% static 'img/bus.png' %}" class="card-img-top mx-auto" alt="...">
                </div>
            </div>
            <div class="col-lg-4 mb-md-0 mb-2 d-flex justify-content-center">
                <div class="card p-3 bg-primary" style="width: 18rem;">
                    <img src="{% static 'img/ship.png' %}" class="card-img-top mx-auto" alt="...">
                </div>
            </div>
            <div class="col-lg-4 mb-md-0 mb-2 d-flex justify-content-center">
                <div class="card p-3 bg-primary" style="width: 18rem;">
                    <img src="{% static 'img/train.png' %}" class="card-img-top mx-auto" alt="...">
                </div>
            </div>
        </div>
    </div>
</section>

<section class="search-section bg-primary">
    <div class="container" id='search_container'>
        <div class="row p-5">
            {% comment %} <form method="POST" action="{% url 'website:orders:search_trip' %}"> {% endcomment %}
                {% csrf_token %}
                {{ search_form }}
                
                <button type="submit" class="btn btn-secondary" id="searchTripBtn">Submit</button>
            {% comment %} </form> {% endcomment %}
        </div>
    </div>
</section>

{% endblock %}

{% block extra_js %}
<script>
    
    $(document).ready(function () {

        $(document).on('click', '#searchTripBtn', function(e) {
            const post_minute = $('#id_date_time_minute').val()

            $.ajax({
                type: "POST",
                url: "{% url 'website:orders:search_trip' %}",
                data: {
                    origin: $('#id_origin').val(),
                    destination: $('#id_destination').val(),
                    transportation: $('#id_transportation').val(),
                    day: $('#id_date_time_day').val(),
                    month: $('#id_date_time_month').val(),
                    year: $('#id_date_time_year').val(),
                    hour: $('#id_date_time_hour').val(),
                    minute: (post_minute == 0) ? post_minute + '0' : post_minute,
                    csrfmiddlewaretoken: '{{ csrf_token }}'
                },
                dataType: "json",
                success: function (response) {
                    if (response.status_code == 200) {
                        
                        $('#q_result').remove()
                        $('#search_container').append(`
                            <div class="row p-5" id='q_result'>
                            </div>
                        `)

                        $.each(response.data, function(key, dt) {
                            $('#q_result').append(`
                                <div class="col-md-6">
                                    <div class="card mb-3">
                                        <h5 class="card-header">`+ dt.transportation__name +`</h5>
                                        <div class="card-body">
                                            <h5 class="card-title">`+ dt.origin +` - `+ dt.destination +`</h5>
                                            <p class="card-text">Jadwal: `+ dt.departure_date +` (`+ dt.departure_time +`)</p>
                                            <p class="card-text">Harga Tiket: Rp`+ dt.price +`</p>
                                            <small>Slot Penumpang: `+ dt.available_seats +`</small>
                                            <a href="#" class="btn btn-primary">Pesan</a>
                                        </div>
                                    </div>
                                </div>
                            `)
                        });

                    } else {
                        $('#q_result').remove()
                        $('#search_container').append(`
                            <div class="row p-5" id='q_result'>
                            </div>
                        `)
                        $('#q_result').append(`
                            <div class="col-md-6">
                                <div class="card mb-3">
                                    <div class="card-body">
                                        <h5 class="card-title">`+ response.message +`</h5>
                                    </div>
                                </div>
                            </div>
                        `)
                    }
                }
            })
        });

    })

</script>
{% endblock  %}

templates/website/login.html
{% extends 'base.html' %}

{% block content %}
    <div class="container masthead">
        <div class="row">
            <div class="col-md-6 mx-auto p-md-5 bg-primary">
                <h1 class='text-center text-light'>Halaman Login</h1>
                <div class="card p-md-5">
                    {% include 'website/form.html' %}
                    <p class="mt-3">Belum punya akun? <a href="{% url 'website:register' %}">Daftar</a></p>
                </div>
            </div>
        </div>
    </div>
{% endblock  %}

templates/website/register.html
{% extends 'base.html' %}

{% block content %}
    <div class="container masthead">
        <div class="row">
            <div class="col-md-6 mx-auto p-md-5 bg-primary">
                <h1 class='text-center text-light'>Halaman Registrasi</h1>
                <div class="card p-md-5">
                    {% include 'website/form.html' %}
                </div>
            </div>
        </div>
    </div>
{% endblock  %}